Repository AY2425S2-CS2103T-T08-3/tp, pull requests merged in 2025-03, with the labels that each got.

#39 Add alicia photo
  docs/images/alicia.png
Labels: priority.High

#43 Update alicia aboutus
  docs/AboutUs.md
  docs/images/rannn367.png
  docs/team/rannn367.md
Labels: priority.High

#23 Update Darren AboutUs
  docs/AboutUs.md
  docs/team/loyaltypollution.md
Labels: priority.High

#25 Add Victor AboutUs
  docs/AboutUs.md
  docs/team/whitebear82.md
Labels: priority.High

#29 Update Justin's AboutUs page
  docs/AboutUs.md
  docs/team/jsjk112344.md
Labels: priority.High

#44 Update alicia aboutus
  docs/images/rannn367.png
Labels: priority.High

#45 Add UI Mockup
  docs/images/Ui.png
Labels: priority.High

#47 Acknowledge original source
  README.md
Labels: priority.High

#49 Branch add user stories dg
  docs/DeveloperGuide.md
Labels: priority.High

#50 Branch add target user dg
  docs/DeveloperGuide.md
  docs/images/Persona.png
Labels: priority.High

#51 Branch add use cases dg
  docs/DeveloperGuide.md
Labels: priority.High

#52 Branch add nfrdg
  docs/DeveloperGuide.md
Labels: priority.High

#53 Branch add glossary dg
  docs/DeveloperGuide.md
Labels: priority.High

#59 Branch add staff command
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniqueStaffList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateStaffException.java
  src/main/java/seedu/address/model/person/exceptions/StaffNotFoundException.java
Labels: type.Task, priority.High

#85 Add customerdelete command for deleting customers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCustomerCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: priority.High

#97 Update GUI to only include staff and customer
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/StaffListCard.fxml
Labels: priority.High

#98 Upgrade test for GUI
  src/main/java/seedu/address/MainApp.java
  src/test/java/seedu/address/DefaultAppLauncher.java
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/TestAppLauncher.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#99 Branch delete staff command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteStaffCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
Labels: type.Task, priority.High

#109 Change display information formatting GUI
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/java/seedu/address/ui/StaffCard.java
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/StaffListCard.fxml
Labels: type.Task, priority.High

#114 Toggle theme
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#106 Branch points add command
  src/main/java/seedu/address/logic/commands/PointsAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PointsAddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
Labels: priority.High

#116 Add drink class
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/DrinkAddCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DrinkAddCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/drink/Drink.java
  src/main/java/seedu/address/model/drink/DrinkCatalog.java
  src/main/java/seedu/address/model/drink/ReadOnlyDrinkCatalog.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/DrinkCatalogStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedDrink.java
  src/main/java/seedu/address/storage/JsonDrinkCatalogStorage.java
  src/main/java/seedu/address/storage/JsonSerializableDrinkCatalog.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonDrinkCatalogStorageTest/invalidDrinkCatalog.json
  src/test/data/JsonDrinkCatalogStorageTest/malformedDrinkCatalog.json
  src/test/data/JsonDrinkCatalogStorageTest/notJsonFormat.json
  src/test/data/JsonDrinkCatalogStorageTest/tempDrinkCatalog.json
  src/test/data/JsonDrinkCatalogStorageTest/validDrinkCatalog.json
  src/test/java/seedu/address/DefaultAppLauncher.java
  src/test/java/seedu/address/TestAppLauncher.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DrinkAddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/DrinkAddCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/drink/DrinkCatalogTest.java
  src/test/java/seedu/address/model/drink/DrinkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDrinkTest.java
  src/test/java/seedu/address/storage/JsonDrinkCatalogStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/DrinkBuilder.java
  src/test/java/seedu/address/testutil/TypicalDrinks.java
Labels: priority.High

#117 Add purchase command
  src/main/java/seedu/address/logic/commands/PurchaseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/PurchaseCommandParser.java
  src/test/java/seedu/address/logic/commands/PurchaseCommandTest.java
  src/test/java/seedu/address/logic/parser/PurchaseCommandParserTest.java
Labels: priority.High

#120 Fix save drink
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Task, priority.High

#122 Display drinks
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/drink/DrinkCatalog.java
  src/main/java/seedu/address/model/drink/UniqueDrinkList.java
  src/main/java/seedu/address/model/drink/exceptions/DrinkNotFoundException.java
  src/main/java/seedu/address/model/drink/exceptions/DuplicateDrinkException.java
  src/main/java/seedu/address/ui/DrinkCard.java
  src/main/java/seedu/address/ui/DrinkListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DrinkListCard.fxml
  src/main/resources/view/DrinkListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/drink/DrinkCatalogTest.java
Labels: type.Task, priority.High

#125 Add PointsAddCommand test
  src/test/java/seedu/address/logic/commands/PointsAddCommandTest.java
  src/test/java/seedu/address/logic/parser/PointsAddCommandParserTest.java
Labels: priority.High

#143 Branch test staff fields
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/HoursWorked.java
  src/main/java/seedu/address/model/person/PerformanceRating.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/ShiftTiming.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/StaffId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStaff.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddStaffCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/HoursWorkedTest.java
  src/test/java/seedu/address/model/person/PerformanceRatingTest.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/model/person/ShiftTimingTest.java
  src/test/java/seedu/address/model/person/StaffIdTest.java
  src/test/java/seedu/address/model/person/StaffTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStaffTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/StaffBuilder.java
  src/test/java/seedu/address/testutil/TypicalStaff.java
Labels: type.Task, priority.Medium, severity.Medium

#147 Branch test customer fields
  src/main/java/seedu/address/logic/commands/PointsAddCommand.java
  src/main/java/seedu/address/logic/commands/PurchaseCommand.java
  src/main/java/seedu/address/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/CustomerId.java
  src/main/java/seedu/address/model/person/FavouriteItem.java
  src/main/java/seedu/address/model/person/RewardPoints.java
  src/main/java/seedu/address/model/person/TotalSpent.java
  src/main/java/seedu/address/model/person/VisitCount.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PointsAddCommandTest.java
  src/test/java/seedu/address/logic/commands/PurchaseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCustomerCommandParserTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/UniqueCustomerListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/testutil/CustomerBuilder.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
Labels: type.Task, type.Bug, priority.High, severity.Medium

#148 Add More Tests
  src/test/java/seedu/address/model/person/CustomerIdTest.java
  src/test/java/seedu/address/model/person/FavouriteItemTest.java
  src/test/java/seedu/address/model/person/RewardPointsTest.java
  src/test/java/seedu/address/model/person/TotalSpentTest.java
Labels: type.Task, priority.Medium, severity.Medium

#146 Add editstaff command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStaffDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
  src/test/java/seedu/address/testutil/TypicalStaff.java
Labels: priority.Medium

#155 Add suggestion for incorrect commands
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.Low, severity.Medium

#163 Add UI tests
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High

#165 Add shortcut for customeradd command
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddCustomerCommandParserTest.java
Labels: type.Enhancement, priority.Low, severity.VeryLow

#167 Remove Food TypicalDrinks
  src/test/java/seedu/address/testutil/TypicalDrinks.java
Labels: type.Bug, priority.Medium, severity.Medium

#168 Edit ug customer
  docs/UserGuide.md
  docs/images/UG_Ui_Images/after_customeradd.png
  docs/images/UG_Ui_Images/after_customerdelete.png
  docs/images/UG_Ui_Images/after_purchase.png
  docs/images/UG_Ui_Images/before_customeradd.png
  docs/images/UG_Ui_Images/before_customerdelete.png
  docs/images/UG_Ui_Images/before_purchase.png
Labels: priority.High

#172 Remove Food SampleDataUtil
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, priority.Medium, severity.VeryLow

#175 Add Staff Commands UG
  docs/UserGuide.md
  docs/images/UG_Ui_Images/after_customeraddshortcut.png
  docs/images/UG_Ui_Images/after_hoursadd.png
  docs/images/UG_Ui_Images/after_staffadd.png
  docs/images/UG_Ui_Images/after_staffaddshortcut.png
  docs/images/UG_Ui_Images/after_staffdelete.png
  docs/images/UG_Ui_Images/before_customeraddshortcut.png
  docs/images/UG_Ui_Images/before_hoursadd.png
  docs/images/UG_Ui_Images/before_staffadd.png
  docs/images/UG_Ui_Images/before_staffaddshortcut.png
  docs/images/UG_Ui_Images/before_staffdelete.png
  docs/img.png
Labels: type.Task, priority.Low

#178 Make changes to UG
  docs/UserGuide.md
  docs/images/UG_Ui_Images/after_drinkadd.png
  docs/images/UG_Ui_Images/after_staffedit.png
  docs/images/UG_Ui_Images/before_drinkadd.png
  docs/images/UG_Ui_Images/before_staffedit.png
  docs/images/UG_Ui_Images/initial_drink.png
  docs/images/UG_Ui_Images/initial_staff.png
  docs/images/UG_Ui_Images/welcome_screen.png
Labels: priority.Medium

#180 Make changes to readme
  docs/index.md
Labels: priority.High, priority.Medium

#181 edit readme some more
  README.md
  docs/index.md
Labels: priority.Medium

#183 Edit drink output
  build.gradle
  docs/images/UG_Ui_Images/after_drinkadd.png
  src/main/java/seedu/address/model/drink/Drink.java
  src/test/java/seedu/address/model/drink/DrinkTest.java
Labels: priority.High

#193 Update Design UI Logic Model DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/DrinkCatalog.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/DrinkCatalogStorage.java
  src/main/java/seedu/address/storage/JsonSerializableDrinkCatalog.java
  src/test/java/seedu/address/logic/commands/DrinkAddCommandTest.java
  src/test/java/seedu/address/logic/commands/PurchaseCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/drink/DrinkCatalogTest.java
  src/test/java/seedu/address/storage/JsonDrinkCatalogStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalDrinks.java
Labels: type.Task, priority.High

#198 Edit dg uml
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteCustomerSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/PurchaseSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: priority.High

#200 Fix issues due to incorrect naming
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCustomerSequenceDiagram.puml
Labels: priority.High

#201 Update drink command
  src/main/java/seedu/address/logic/commands/AddDrinkCommand.java
  src/main/java/seedu/address/logic/parser/AddDrinkCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddDrinkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDrinkCommandParserTest.java
Labels: priority.High

#206 Fix display messages and update help URL
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High

#209 Update icon for app
  src/main/resources/images/favicon.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#211 Add Logging AddStaffCommand
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
Labels: type.Task, priority.Low

#214 Edit ug purchase
  docs/SettingUp.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/images/UG_Ui_Images/after_purchase.png
  docs/images/UG_Ui_Images/after_purchase_redeem.png
  docs/images/UG_Ui_Images/before_purchase.png
  docs/images/UG_Ui_Images/before_purchase_redeem.png
Labels: priority.High

#215 Add Assertions
  build.gradle
Labels: type.Task, priority.High

#227 Ensure test does not override json
  src/test/java/seedu/address/MainAppTest.java
Labels: priority.Medium

#225 Refactor nested static class (EditPersonDescriptor and EditStaffDescriptor)
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/main/java/seedu/address/logic/parser/descriptors/EditCustomerDescriptor.java
  src/main/java/seedu/address/logic/parser/descriptors/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/parser/descriptors/EditStaffDescriptor.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/testutil/EditCustomerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditStaffDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium

#231 Refactor address book
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/Staff.java
  src/main/java/seedu/address/model/person/UniqueCustomerList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/UniqueStaffList.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStaffCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/StaffTest.java
  src/test/java/seedu/address/model/person/UniqueCustomerListTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/UniqueStaffListTest.java
Labels: priority.Low

#237 Branch delete drink
  bin/main/seedu/address/logic/Messages.class
  bin/main/seedu/address/logic/commands/DeleteDrinkCommand.class
  bin/main/seedu/address/logic/parser/AddressBookParser.class
  bin/main/seedu/address/logic/parser/DeleteDrinkCommandParser.class
  bin/test/seedu/address/logic/commands/CommandTestUtil.class
  bin/test/seedu/address/logic/commands/DeleteDrinkCommandTest.class
  bin/test/seedu/address/logic/parser/DeleteDrinkCommandParserTest.class
  bin/test/seedu/address/testutil/TypicalIndexes.class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteDrinkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteDrinkCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteDrinkCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteDrinkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#240 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteDrinkSequenceDiagram.puml
  docs/images/UG_Ui_Images/after_drinkdelete.png
  docs/images/UG_Ui_Images/before_drinkdelete.png
  docs/images/helpMessage.png
Labels: priority.High

#251 Remove unecessary fields in drink details panel
  bin/main/seedu/address/model/Model.class
  bin/main/seedu/address/ui/DrinkDetailPanel.class
  bin/main/view/DrinkDetailView.fxml
  src/main/java/seedu/address/ui/DrinkDetailPanel.java
  src/main/resources/view/DrinkDetailView.fxml
Labels: priority.Medium, alpha-bug

#253 Update DG Staff Customer
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCustomerSequenceDiagram.puml
  docs/diagrams/AddStaffSequenceDiagram.puml
  docs/diagrams/DeleteStaffSequenceDiagram.puml
Labels: type.Task, priority.High

#257 Add extra tests
  bin/test/seedu/address/logic/commands/DeleteCustomerCommandTest.class
  bin/test/seedu/address/logic/commands/DeleteStaffCommandTest.class
  bin/test/seedu/address/logic/parser/DeleteCustomerCommandParserTest.class
  bin/test/seedu/address/logic/parser/DeleteDrinkCommandParserTest.class
  bin/test/seedu/address/logic/parser/DeleteStaffCommandParserTest.class
  src/test/java/seedu/address/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDrinkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteStaffCommandParserTest.java
Labels: priority.High
