Repository AY2425S2-CS2103T-T08-3/tp, pull requests merged in 2025-04, with the labels that each got.

#260 Update default JavaFX window icon
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#259 Update all UG UI images based on new UI
  docs/images/UG_Ui_Images/after_customeradd.png
  docs/images/UG_Ui_Images/after_customeraddshortcut.png
  docs/images/UG_Ui_Images/after_customerdelete.png
  docs/images/UG_Ui_Images/after_drinkadd.png
  docs/images/UG_Ui_Images/after_drinkdelete.png
  docs/images/UG_Ui_Images/after_hoursadd.png
  docs/images/UG_Ui_Images/after_purchase.png
  docs/images/UG_Ui_Images/after_purchase_redeem.png
  docs/images/UG_Ui_Images/after_staffadd.png
  docs/images/UG_Ui_Images/after_staffaddshortcut.png
  docs/images/UG_Ui_Images/after_staffdelete.png
  docs/images/UG_Ui_Images/after_staffedit.png
  docs/images/UG_Ui_Images/before_customeradd.png
  docs/images/UG_Ui_Images/before_customeraddshortcut.png
  docs/images/UG_Ui_Images/before_customerdelete.png
  docs/images/UG_Ui_Images/before_drinkadd.png
  docs/images/UG_Ui_Images/before_drinkdelete.png
  docs/images/UG_Ui_Images/before_hoursadd.png
  docs/images/UG_Ui_Images/before_purchase.png
  docs/images/UG_Ui_Images/before_purchase_redeem.png
  docs/images/UG_Ui_Images/before_staffadd.png
  docs/images/UG_Ui_Images/before_staffaddshortcut.png
  docs/images/UG_Ui_Images/before_staffdelete.png
  docs/images/UG_Ui_Images/before_staffedit.png
  docs/images/UG_Ui_Images/initial_drink.png
  docs/images/UG_Ui_Images/initial_staff.png
  docs/images/UG_Ui_Images/welcome_screen.png
Labels: priority.High

#278 Find command
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FindStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/FindStaffCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/FindStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindStaffCommandParserTest.java
Labels: priority.High

#281 Edit purchase command
  bin/main/seedu/address/logic/commands/FindCustomerCommand.class
  bin/main/seedu/address/logic/commands/FindStaffCommand.class
  bin/main/seedu/address/logic/parser/FindCustomerCommandParser.class
  bin/main/seedu/address/logic/parser/FindStaffCommandParser.class
  bin/test/seedu/address/logic/commands/FindCustomerCommandTest.class
  bin/test/seedu/address/logic/commands/FindStaffCommandTest.class
  bin/test/seedu/address/logic/parser/FindCustomerCommandParserTest.class
  bin/test/seedu/address/logic/parser/FindStaffCommandParserTest.class
  bin/test/seedu/address/model/person/TestPerson.class
  bin/test/seedu/address/model/util/CustomerBuilderTest.class
  bin/test/seedu/address/model/util/PersonBuilderTest.class
  bin/test/seedu/address/model/util/StaffBuilderTest.class
  bin/test/seedu/address/model/util/TestPersonBuilder.class
  bin/test/seedu/address/testutil/TypicalAddressBook.class
  src/main/java/seedu/address/logic/parser/PurchaseCommandParser.java
Labels: priority.High, alpha-bug

#283 Edit drinkadd command
  src/main/java/seedu/address/logic/parser/AddDrinkCommandParser.java
Labels: priority.High, alpha-bug

#285 Branch add logging staff
  src/main/java/seedu/address/model/person/Staff.java
Labels: type.Task, priority.High

#287 Add Logging AddCustomerCommand
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
Labels: type.Task, priority.High

#289 Add Logging AddDrinkCommand
  src/main/java/seedu/address/logic/commands/AddDrinkCommand.java
Labels: type.Task, priority.High

#291 Add Logging AddStaffCommand
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
Labels: type.Task, priority.High

#292 Fix case sensitivity for customer/staff id
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/CustomerId.java
  src/main/java/seedu/address/model/person/StaffId.java
  src/test/java/seedu/address/model/person/CustomerIdTest.java
  src/test/java/seedu/address/model/person/StaffIdTest.java
Labels: alpha-bug

#294 Add EditStaff description to DG
  docs/DeveloperGuide.md
  docs/diagrams/EditStaffSequenceDiagram.puml
Labels: priority.High

#301 Implement Model classes for Drink
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/PurchaseCommand.java
  src/main/java/seedu/address/model/drink/Category.java
  src/main/java/seedu/address/model/drink/Drink.java
  src/main/java/seedu/address/model/drink/DrinkName.java
  src/main/java/seedu/address/model/drink/Price.java
  src/main/java/seedu/address/model/person/TotalSpent.java
  src/main/java/seedu/address/storage/JsonAdaptedDrink.java
  src/main/java/seedu/address/ui/DrinkCard.java
  src/main/java/seedu/address/ui/DrinkDetailPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PurchaseCommandTest.java
  src/test/java/seedu/address/model/drink/DrinkNameTest.java
  src/test/java/seedu/address/model/drink/DrinkTest.java
  src/test/java/seedu/address/model/drink/PriceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDrinkTest.java
Labels: priority.High

#304 Add logging Delete Customer and Drink Commands
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDrinkCommand.java
Labels: type.Task, priority.High

#305 Fix Alpha Bug Shortcut commands
  src/main/java/seedu/address/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStaffCommandParser.java
Labels: type.Task, priority.High

#306 Fix Alpha Bug TotalSpent Formatting
  src/main/java/seedu/address/model/person/TotalSpent.java
  src/test/java/seedu/address/model/person/TotalSpentTest.java
Labels: type.Task, priority.High

#307 Fix Alpha Bug Blank Screen
  src/main/java/seedu/address/ui/WelcomeScreen.java
Labels: type.Task, priority.High

#310 Adds images for stafffind, customerfind
  docs/images/UG_Ui_Images/after_customerfind.png
  docs/images/UG_Ui_Images/after_stafffind.png
  docs/images/UG_Ui_Images/before_customerfind.png
  docs/images/UG_Ui_Images/before_stafffind.png
Labels: priority.High

#311 adds customeredit ui images for ug
  docs/images/UG_Ui_Images/after_customeredit.png
  docs/images/UG_Ui_Images/before_customeredit.png
Labels: priority.High

#324 Fix Alpha Bug HelpforShortcutCommands
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
Labels: type.Task, priority.High

#328 Branch fix alpha bug staff customer list
  src/main/java/seedu/address/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/address/logic/commands/ListStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddDrinkCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/ListStaffCommandParser.java
  src/test/java/seedu/address/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/ListStaffCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListStaffCommandParserTest.java
Labels: type.Task, priority.High, alpha-bug

#330 Fix Alpha Bug CaseSensitiveCommands
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task, priority.High, alpha-bug

#332 Fix Alpha Bug LongTextInput
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/CustomerId.java
  src/main/java/seedu/address/model/person/FavouriteItem.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/ShiftTiming.java
  src/main/java/seedu/address/model/person/StaffId.java
Labels: type.Task, priority.High, alpha-bug

#331 Make invalid PerformanceRating error message more specific
  src/main/java/seedu/address/model/person/PerformanceRating.java
Labels: priority.Medium, severity.Medium, alpha-bug

#335 Branch fix alpha bug error message sidcid
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, type.Bug, priority.High, alpha-bug

#333 Fix Alpha Bug InconsistentSpace
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task, type.Bug, priority.High, alpha-bug

#337 Add Alias All Commands
  src/main/java/seedu/address/logic/commands/AddDrinkCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDrinkCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FindStaffCommand.java
  src/main/java/seedu/address/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/address/logic/commands/ListStaffCommand.java
  src/main/java/seedu/address/logic/commands/PurchaseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, type.Task, priority.High

#340 Add Command Usage All Alias
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddDrinkCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDrinkCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FindStaffCommand.java
  src/main/java/seedu/address/logic/commands/PurchaseCommand.java
Labels: type.Enhancement, priority.High

#343 Fix field description in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#345 Fix AlphaBug AutoSwitch
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, alpha-bug

#346 Fix AlphaBug ImmutableVisitCount
  src/main/java/seedu/address/logic/commands/PurchaseCommand.java
  src/main/java/seedu/address/model/person/VisitCount.java
Labels: type.Task, alpha-bug

#349 Fixes minor errors in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#351 Fix Alpha Bug AutoSwitchView
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, type.Bug, priority.High, alpha-bug

#353 update ug with new information and reformat
  bin/main/seedu/address/logic/commands/FindCustomerCommand.class
  bin/main/seedu/address/logic/commands/FindStaffCommand.class
  bin/main/seedu/address/logic/parser/FindCustomerCommandParser.class
  bin/main/seedu/address/logic/parser/FindStaffCommandParser.class
  bin/test/seedu/address/logic/parser/FindCustomerCommandParserTest.class
  bin/test/seedu/address/logic/parser/FindStaffCommandParserTest.class
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: priority.Medium

#355 DG - Storage component, QuickCommands & relevant diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ShortcutCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StorageSequenceDiagram.puml
Labels: priority.High

#359 Revamps model section of dg and relevant diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CustomerModelClassDiagram.puml
  docs/diagrams/DrinkModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelOverviewClassDiagram.puml
  docs/diagrams/PersonModelClassDiagram.puml
  docs/diagrams/StaffModelClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
Labels: priority.High

#360 Adds UI images for purchase shortcut command
  docs/UserGuide.md
  docs/images/UG_Ui_Images/after_purchase_redeemshortcut.png
  docs/images/UG_Ui_Images/after_purchaseshortcut.png
  docs/images/UG_Ui_Images/before_purchase_redeemshortcut.png
  docs/images/UG_Ui_Images/before_purchaseshortcut.png
Labels: priority.High

#361 Updates customer/staff edit images in UG
  docs/images/UG_Ui_Images/after_customeredit.png
  docs/images/UG_Ui_Images/after_staffedit.png
  docs/images/UG_Ui_Images/before_customeredit.png
  docs/images/UG_Ui_Images/before_staffedit.png
Labels: priority.High

#364 Branch fix alpha bug missing u sand ps
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
Labels: alpha-bug

#365 Fix AlphaBug Missing PUMLCustomerEdit
  docs/DeveloperGuide.md
Labels: alpha-bug

#367 Fix AlphaBug UGBugs
  docs/UserGuide.md
Labels: alpha-bug

#371 Fix AlphaBug NotResizable
  src/main/java/seedu/address/ui/MainWindow.java
Labels: alpha-bug

#369 update DG intro
  docs/DeveloperGuide.md
  docs/diagrams/CustomerShortcutCommandSequenceDiagram.puml
  docs/diagrams/PurchaseShortcutCommandSequenceDiagram.puml
  docs/diagrams/ShortcutCommandSequenceDiagram.puml
  docs/diagrams/StaffShortcutCommandSequenceDiagram.puml
  docs/diagrams/StorageSequenceDiagram.puml
Labels: priority.High

#375 Branch fix alpha bug missing app icon
  build.gradle
  docs/images/cafeconnect-icon.png
  src/main/java/seedu/address/ui/WelcomeScreen.java
  src/main/resources/images/cafeconnect-icon.png
Labels: alpha-bug

#377 Fix AlphaBug UGTypoPurchase
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: alpha-bug

#380 Fix AlphaBug DGTypoQC
  docs/DeveloperGuide.md
  docs/diagrams/CustomerShortcutCommandSequenceDiagram.puml
  docs/diagrams/StaffShortcutCommandSequenceDiagram.puml
Labels: alpha-bug

#381 Fix AlphaBug DGTypoQP
  docs/diagrams/PurchaseShortcutCommandSequenceDiagram.puml
Labels: alpha-bug

#385 Tune parameters of fuzzy search
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
Labels: type.Bug

#457 Update UG to fix PE-D bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PersonModelClassDiagram.puml
  docs/images/CafeConnectJar.png
  docs/images/DownloadCafeConnect.png
  docs/images/MacTerminal.jpg
  docs/images/Maccd.jpg
  docs/images/Macfilepath.jpg
  docs/images/Macfilepathinfo.jpg
  docs/images/OpenMacTerminal.jpg
  docs/images/OpenWindowsTerminal.png
  docs/images/WindowsTerminal.png
  docs/images/Windowscd.png
  docs/images/Windowsfilepath.png
  docs/images/searchbar.png
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Documentation, CodeBug

#467 FIx user guide issues
  bin/main/view/CustomerDetailView.fxml
  bin/main/view/StaffDetailView.fxml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  src/main/java/seedu/address/logic/parser/DeleteCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteStaffCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteStaffCommandParserTest.java
Labels: RequiresFixing

#469 Add period to fix issue
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/PersonModelClassDiagram.puml
  docs/images/UG_Ui_Images/after_customeradd.png
  docs/images/UG_Ui_Images/after_customerdelete.png
  docs/images/UG_Ui_Images/after_customeredit.png
  docs/images/UG_Ui_Images/after_quickcustomeradd.png
  docs/images/UG_Ui_Images/after_quickstaffadd.png
  docs/images/UG_Ui_Images/after_staffadd.png
  docs/images/UG_Ui_Images/after_staffdelete.png
  docs/images/UG_Ui_Images/after_staffedit.png
  docs/images/UG_Ui_Images/before_customeradd.png
  docs/images/UG_Ui_Images/before_customerdelete.png
  docs/images/UG_Ui_Images/before_quickcustomeradd.png
  docs/images/UG_Ui_Images/before_quickstaffadd.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddStaffCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/parser/EditCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/descriptors/EditCustomerDescriptor.java
  src/main/java/seedu/address/logic/parser/descriptors/EditPersonDescriptor.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/Staff.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/CustomerTest.java
  src/test/java/seedu/address/model/person/StaffTest.java
  src/test/java/seedu/address/testutil/EditCustomerDescriptorBuilder.java
Labels: type.Documentation

#478 fix staff edit
  src/main/java/seedu/address/logic/commands/EditStaffCommand.java
  src/main/java/seedu/address/logic/parser/EditStaffCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditStaffCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStaffDescriptorBuilder.java
Labels: priority.High

#481 fixed style issues for images
  docs/images/UG_Ui_Images/after_customerfind.png
  docs/images/UG_Ui_Images/after_purchase.png
  docs/images/UG_Ui_Images/after_stafffind.png
  docs/images/UG_Ui_Images/before_customerfind.png
  docs/images/UG_Ui_Images/before_purchase.png
  docs/images/UG_Ui_Images/before_stafffind.png
Labels: priority.High

#471 Branch fix ped bugs long address
  src/main/resources/view/CustomerDetailView.fxml
  src/main/resources/view/StaffDetailView.fxml
Labels: type.Bug

#482 Update UG and email validation
  bin/main/view/CustomerDetailView.fxml
  bin/main/view/StaffDetailView.fxml
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: CodeBug

#486 Fix se
  src/main/java/seedu/address/logic/parser/QuickAddCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/QuickAddStaffCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/ShiftTiming.java
  src/test/java/seedu/address/logic/parser/QuickAddCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/QuickAddStaffCommandParserTest.java
Labels: priority.High

#488 UG update
  docs/UserGuide.md
  docs/images/UG_Ui_Images/after_purchase.png
  docs/images/UG_Ui_Images/after_quickcustomeradd.png
  docs/images/UG_Ui_Images/after_quickpurchase.png
  docs/images/UG_Ui_Images/after_quickstaffadd.png
  docs/images/UG_Ui_Images/before_purchase.png
  docs/images/UG_Ui_Images/before_quickcustomeradd.png
  docs/images/UG_Ui_Images/before_quickpurchase.png
  docs/images/UG_Ui_Images/before_quickstaffadd.png
  docs/team/johndoe.md
Labels: priority.High
